"""LLM client with a deterministic mock fallback.

The orchestrator never hard-depends on a network call: if no real backend is
configured (``CLAWMES_LLM=mock`` or no API key), responses are generated by a
deterministic, role-aware mock so the whole system runs offline and tests are
reproducible. Swap ``_complete_real`` for your local LLM / cloud fallback.
"""
from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass, field

from . import config as cfg
from .providers import CATALOG, chat


@dataclass
class Usage:
    """Token accounting for a single completion."""
    prompt_tokens: int = 0
    completion_tokens: int = 0

    @property
    def total(self) -> int:
        return self.prompt_tokens + self.completion_tokens


@dataclass
class LLMClient:
    """Minimal completion client.

    Parameters
    ----------
    model:
        Logical model name (informational in mock mode).
    mode:
        ``"mock"`` (default offline) or ``"real"``. Controlled by env
        ``CLAWMES_LLM`` when not set explicitly.
    """
    model: str = "clawmes-local"
    mode: str = field(default_factory=lambda: os.environ.get("CLAWMES_LLM", "auto"))

    def _effective_mode(self) -> str:
        if self.mode in ("mock", "real"):
            return self.mode
        return "real" if cfg.is_configured() else "mock"  # auto

    def complete(self, prompt: str, system: str | None = None) -> tuple[str, Usage]:
        if self._effective_mode() == "real":
            return self._complete_real(prompt, system)
        return self._complete_mock(prompt, system)

    # ------------------------------------------------------------------ mock
    @staticmethod
    def _estimate_tokens(text: str) -> int:
        # ~4 chars/token heuristic; good enough for budgeting in mock mode.
        return max(1, len(text) // 4)

    def _complete_mock(self, prompt: str, system: str | None) -> tuple[str, Usage]:
        seed = hashlib.sha256(((system or "") + prompt).encode("utf-8")).hexdigest()[:8]
        role = "agent"
        if system:
            low = system.lower()
            for r in ("researcher", "executor", "critic", "trader", "synthesizer"):
                if r in low:
                    role = r
                    break
        body = self._mock_body(role, prompt, seed)
        usage = Usage(
            prompt_tokens=self._estimate_tokens((system or "") + prompt),
            completion_tokens=self._estimate_tokens(body),
        )
        return body, usage

    @staticmethod
    def _mock_body(role: str, prompt: str, seed: str) -> str:
        task = prompt.strip().splitlines()[0][:120] if prompt.strip() else "(empty task)"
        templates = {
            "researcher": (
                f"Finding [{seed}]: surveyed sources on '{task}'. "
                "Key signal: convergence of multi-agent orchestration toward "
                "supervisor+worker topologies with isolated memory subspaces. "
                "Confidence: 0.72."
            ),
            "executor": (
                f"Action [{seed}]: executed sub-task for '{task}'. "
                "Produced concrete artifact; no side effects outside sandbox. "
                "Status: success."
            ),
            "critic": (
                f"Critique [{seed}] of '{task}': watch unbounded recursion and "
                "token blowups; require depth caps and per-swarm budgets. "
                "Risk score: 0.4 (acceptable with governance)."
            ),
            "trader": (
                f"Signal [{seed}] for '{task}': estimated edge +3.1%, "
                "position sizing 1.5% bankroll, stop at -1.2%. Hold-to-converge."
            ),
            "synthesizer": (
                f"Synthesis [{seed}]: merged worker outputs for '{task}' into a "
                "single recommendation with majority agreement and flagged dissent."
            ),
        }
        return templates.get(role, f"Result [{seed}] for '{task}'.")

    # ------------------------------------------------------------------ real
    def _complete_real(self, prompt: str, system: str | None) -> tuple[str, Usage]:
        """Call the provider configured via `clawmes onboard`.

        Returns (text, Usage) so swarm token budgeting still works; usage is
        estimated from text length (~4 chars/token).
        """
        model_ref = cfg.get_default_model()
        if not model_ref:
            raise RuntimeError(
                "No provider configured. Run 'clawmes onboard' to pick a "
                "provider and model (or set CLAWMES_LLM=mock for offline use)."
            )
        provider_id, model = cfg.split_model_ref(model_ref)
        provider = CATALOG.get(provider_id)
        entry = cfg.provider_entry(provider_id) or {}
        if not provider:
            raise RuntimeError(f"Unknown provider '{provider_id}' in config.")
        api_key = cfg.resolve_api_key(provider_id)
        if provider.needs_key and not api_key:
            raise RuntimeError(
                f"Missing API key for '{provider_id}'. Set {provider.key_env} or "
                f"re-run 'clawmes onboard' and paste the key."
            )
        text = chat(provider=provider, model=model, prompt=prompt, system=system,
                    api_key=api_key, base_url=entry.get("baseUrl"))
        usage = Usage(
            prompt_tokens=self._estimate_tokens((system or "") + prompt),
            completion_tokens=self._estimate_tokens(text),
        )
        return text, usage
